CREATE SCHEMA IF NOT EXISTS INTELAF;
USE INTELAF;

CREATE TABLE IF NOT EXISTS TIENDA(
codigo VARCHAR(45) NOT NULL,
nombre VARCHAR(45) NOT NULL,
direccion varchar(45) NOT NULL,
telefono1 VARCHAR(13) NOT NULL,
telefono2 VARCHAR(13),
correo VARCHAR(45),
horario VARCHAR(45),
PRIMARY KEY(codigo)
);

CREATE TABLE IF NOT EXISTS TIEMPO_ENTRE_TIENDAS(
ID INT NOT NULL AUTO_INCREMENT,
tiempo INT NOT NULL,
tienda_destino VARCHAR(45) NOT NULL,
tienda_origen VARCHAR(45) NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(tienda_origen) REFERENCES TIENDA(codigo)
);

CREATE TABLE IF NOT EXISTS EMPLEADO(
codigo VARCHAR(45) NOT NULL,
nombre VARCHAR(45) NOT NULL,
telefono VARCHAR(13) NOT NULL,
NIT VARCHAR(13),
DPI VARCHAR(13) NOT NULL,
correo VARCHAR(45) NOT NULL,
direccion VARCHAR(45) NOT NULL,
PRIMARY KEY(codigo)
);

CREATE TABLE IF NOT EXISTS CLIENTE(
NIT VARCHAR(45) NOT NULL,
nombre VARCHAR(45) NOT NULL,
telefono VARCHAR(13) NOT NULL,
DPI VARCHAR(13),
credito DOUBLE,
correo VARCHAR(45),
direccion VARCHAR(45),
PRIMARY KEY(NIT)
);

CREATE TABLE IF NOT EXISTS PRODUCTO(
codigo VARCHAR(45) NOT NULL,
nombre VARCHAR(45) NOT NULL,
fabricante VARCHAR(45) NOT NULL,
cantidad INT NOT NULL,
precio DOUBLE NOT NULL,
descripcion VARCHAR(200),
garantia INT,
codigo_tienda VARCHAR(45) NOT NULL,
PRIMARY KEY(codigo),
FOREIGN KEY(codigo_tienda) REFERENCES TIENDA(codigo)
);

CREATE TABLE IF NOT EXISTS FACTURA(
codigo INT NOT NULL AUTO_INCREMENT,
fecha DATE NOT NULL,
total DOUBLE NOT NULL,
codigo_cliente VARCHAR(13) NOT NULL,
codigo_tienda VARCHAR(45) NOT NULL,
PRIMARY KEY(codigo),
FOREIGN KEY(codigo_cliente) REFERENCES CLIENTE(NIT),
FOREIGN KEY(codigo_tienda) REFERENCES TIENDA(codigo)
);

CREATE TABLE IF NOT EXISTS VENTA(
ID INT NOT NULL AUTO_INCREMENT,
cantidad INT NOT NULL,
precio DOUBLE NOT NULL,
codigo_producto VARCHAR(45) NOT NULL,
codigo_factura INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(codigo_producto) REFERENCES PRODUCTO(codigo),
FOREIGN KEY(codigo_factura) REFERENCES FACTURA(codigo)
);

CREATE TABLE IF NOT EXISTS PEDIDO(
codigo INT NOT NULL AUTO_INCREMENT,
fecha DATE NOT NULL,
cantidad INT NOT NULL,
total DOUBLE NOT NULL,
anticipo DOUBLE NOT NULL,
codigo_producto VARCHAR(45) NOT NULL,
codigo_cliente VARCHAR(13) NOT NULL,
codigo_tienda VARCHAR(45) NOT NULL,
tiempo_envio INT NOT NULL,
PRIMARY KEY(codigo),
FOREIGN KEY(codigo_producto) REFERENCES PRODUCTO(codigo),
FOREIGN KEY(codigo_cliente) REFERENCES CLIENTE(NIT),
FOREIGN KEY(codigo_tienda) REFERENCES TIENDA(codigo),
FOREIGN KEY(tiempo_envio) REFERENCES TIEMPO_ENTRE_TIENDAS(ID)
);

CREATE TABLE IF NOT EXISTS RECIBO(
ID INT NOT NULL AUTO_INCREMENT,
fecha_ingreso DATE NOT NULL,
codigo_tienda VARCHAR(45) NOT NULL,
codigo_pedido INT NOT NULL,
PRIMARY KEY(ID),
FOREIGN KEY(codigo_tienda) REFERENCES TIENDA(codigo),
FOREIGN KEY(codigo_pedido) REFERENCES PEDIDO(codigo)
);